### ISSUE TITLE
Unable to fetch twitter profile

### ISSUE THREAD

**Issue by midhunlanware** [superfaceai/passport-twitter-oauth2#41]
After successful authorization it gives Unable to fetch twitter profile

**Comment by linxux** [comment]
This issue comes up occasionally...
It will disappear if retry the login process.

And here is the scopes,
> { scope: ['tweet.read', 'users.read', 'offline.access'] }

```
2024-01-05 02:02:08 | default | error | InternalOAuthError: Failed to fetch user profile
    at /.../...//node_modules/@superfaceai/passport-twitter-oauth2/dist/strategy.js:111:29
    at passBackControl (/.../...//node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/.../...//node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:488:12)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by linxux** [comment]
Okay, it may be a rate limit issue.

Logging the error,
```json
  oauthError: {
    statusCode: 429,
    data: '{"title":"Too Many Requests","detail":"Too Many Requests","type":"about:blank","status":429}'
  }
```

Then how to dynamic change the `skipUserProfile` to `false`
