### ISSUE TITLE
TokenError: Missing valid authorization header

### ISSUE THREAD

**Issue by cSarcasme** [superfaceai/passport-twitter-oauth2#42]
I have search a lot a solution for my issue but i dont find it!

you are my last hope :) !

error i have when i connect with twitter i arrive to the twitter page and give the authorization on my twitter account after that i have this error:

TokenError: Missing valid authorization header
    at OAuth2Strategy.parseErrorResponse (C:\Users\haatman\Desktop\dbq2formydev-main\dbq2formydev-main\bck\node_modules\passport-oauth2\lib\strategy.js:373:12)
    at OAuth2Strategy._createOAuthError (C:\Users\haatman\Desktop\dbq2formydev-main\dbq2formydev-main\bck\node_modules\passport-oauth2\lib\strategy.js:420:16)
    at C:\Users\haatman\Desktop\dbq2formydev-main\dbq2formydev-main\bck\node_modules\passport-oauth2\lib\strategy.js:177:45
    at C:\Users\haatman\Desktop\dbq2formydev-main\dbq2formydev-main\bck\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\haatman\Desktop\dbq2formydev-main\dbq2formydev-main\bck\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\haatman\Desktop\dbq2formydev-main\dbq2formydev-main\bck\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    
    
    my code:
    
    **middleware**

```javascript
    require('dotenv').config();
const passport = require('passport');
const Strategy = require('@superfaceai/passport-twitter-oauth2').Strategy;
const TwitterUser = require('../models/TwitterUser');
const jwt = require('jsonwebtoken');

passport.serializeUser((user, done) => {
	if (user.provider === 'twitter') {
		//console.log('Twitter-userSerialize', user);
		//console.log('Twitter-userID', user.id);
		done(null, { type: 'twitterUser', idTwitter: user.id });
	} else {
		// L'utilisateur ne provient pas de Twitter, ne rien faire
		done();
	}
});

// Désérialise l'utilisateur à partir de la session
passport.deserializeUser(async (serializedUser, done) => {
	if (serializedUser.type === 'twitterUser') {
		try {
			let user = await TwitterUser.findById(serializedUser.idTwitter);
			// console.log('twitterUser', user)
			done(null, user);
		} catch (error) {
			done(error, null);
		}
	} else {
		done();
	}
});

// Use the Twitter OAuth2 strategy within Passport
passport.use(
	// <2> Strategy initialization
	new Strategy(
		{
			clientID: process.env.TWITTER_CLIENT_ID,
			clientSecret: process.env.TWITTER_CLIENT_ID_SECRET,
			clientType: 'confidential',
			callbackURL: process.env.CALLBACK_TWITTER,
		},
		// <3> Verify callback
		async (accessToken, refreshToken, profile, done) => {
			//console.log(profile);

			try {
				const { id, _json } = profile;
				const name = _json.name;
				const screen_name = _json.screen_name;
				const followers_count = _json.followers_count;
				const findUser = await TwitterUser.findOne({ twitterId: id });

				if (findUser) {
					console.log('access token', accessToken);
					console.log('tokenSecret', refreshToken);
					findUser.accessToken = jwt.sign(
						{ accessToken },
						process.env.JWT_TWITTER_CLIENT_TOKEN
					);
					findUser.refreshToken = jwt.sign(
						{ refreshToken },
						process.env.JWT_TWITTER_CLIENT_TOKEN_SECRET
					);

					await findUser.save();

					return done(null, findUser);
				} else {
					console.log('access token', accessToken);
					console.log('tokenSecret', refreshToken);
					//console.log('pofileTest',id,name, screen_name,followers_count)
					const newUser = await TwitterUser.create({
						twitterId: id,
						userName: name,
						screenName: screen_name,
						followersCount: followers_count,
						accessToken: jwt.sign(
							{ accessToken },
							process.env.JWT_TWITTER_CLIENT_TOKEN
						),
						refreshToken: jwt.sign(
							{ refreshToken },
							process.env.JWT_TWITTER_CLIENT_TOKEN_SECRET
						),
					});
					return done(null, newUser);
				}
			} catch (error) {
				console.error(error);
				return done(error, null);
			}
		}
	)
);

module.exports = passport;

``` 

**my roads:**

```javascript
require('dotenv').config();
const express = require('express');
const passport = require('passport');
const isAuthenticated = require('../../middleware/authorized');

const router = express.Router();

router.get(
	'/twitter',
	passport.authenticate('twitter', {
		scope: [
			'tweet.read',
			'users.read',
			'like.read',
			'follows.read',
			'space.read',
			'list.read',
			'offline.access',
		],
	}),
	(req, res) => {
		res.status(200);
	}
);

router.get(
	'/twitter/redirect',
	passport.authenticate('twitter', {
		failureRedirect: 'http://localhost:3000/',
	}),
	(req, res) => {
		// Affectez les données de session à req.session.twitterSession
		res.redirect('http://localhost:3000/');
	}
);

router.get('/status', isAuthenticated, (req, res) => {
	//console.log(req);
	if (req.user) {
		res.status(200).send(req.user);
	} else {
		res.status(401).json({ message: 'Unauthorized' });
	}
});
module.exports = router;

``` 

**express-session and save cookie into mongoose**

```javascript
// appTwitter.js
require('dotenv').config();
const express = require('express');
const session = require('express-session');
const passport = require('passport');
const MongoStore = require('connect-mongo');
require('./middleware/twitter');

const twitterSession = express();

twitterSession.use(
	session({
		secret: process.env.SESSION_SECRET_TWITTER,
		resave: false,
		saveUninitialized: false,
		cookie: {
			maxAge: 6000 * 60 * 24 * 7,
		},
		store: MongoStore.create({
			mongoUrl:
				**********************************************************************************,
			collectionName: 'sessionTwitter',
		}),
		name: 'twitterConnect',
	})
);

twitterSession.use(passport.initialize());

twitterSession.use(passport.session());
// ... autres configurations spécifiques à Twitter

module.exports = twitterSession;
``` 

I hope someone can help me i ty by advance :)

If you need other information tell me.

**Comment by cSarcasme** [comment]
Anyone to help me please ?

I ty by advance.

**Comment by janhalama** [comment]
Hi, I will look at it today and give you some answers.

Jan

**Comment by cSarcasme** [comment]
thanks a lot mr janhalama i will wait

**Comment by janhalama** [comment]
From the call stack you provided it looks like that Twitter strategy is not configured properly. Specifically [custom headers](https://github.com/superfaceai/passport-twitter-oauth2/blob/6001cbbf26e590c904964f112366c1c5eb5bad57/src/strategy.ts#L80) are not configured. 

Custom headers are configured if the `clientType` option is set to `confidential` in the strategy constructor. From the code snippets you provided I can not say where exactly is the problem.

What is the version of @superfaceai/passport-twitter-oauth2 lib you have installed?
Did you try the [basic example app](https://github.com/superfaceai/passport-twitter-oauth2/tree/main/examples/basic-usage) with your Twitter App configuration?

**Comment by janhalama** [comment]
> ty for your quick answer i will try with the basic example and come back to you with the result and maybe it will help me find the solution.

Or, if you can provide a minimum reproducible example, I can help.

> Also i have that intalled "@superfaceai/passport-twitter-oauth2": "^1.2.3",>
> i think it i the last version ?

Yes it is the latest version, there was an update in the library recently, but as you are on the latest version it is not the case.

**Comment by cSarcasme** [comment]
ia am on it now i had to finish a other part of my code before to come back to that so i am on it i look little more on my side and if i dont find i will provide you a minimum reproductible sorry for the delay.

Now i don' t do other dev thing until i find the solution ;) haha ty for your time

**Comment by cSarcasme** [comment]
So i have find the issue ty to you you put me on the road for resolve my mistake it was the customHeaders

This the final code with the strategy in it resolve.

```
/ Use the Twitter OAuth2 strategy within Passport
passport.use(
	// <2> Strategy initialization
	new Strategy(
		{
			clientID: process.env.TWITTER_CLIENT_ID,
			clientSecret: process.env.TWITTER_CLIENT_ID_SECRET,
			clientType: 'confidential',
			callbackURL: process.env.CALLBACK_TWITTER,
		},
		// <3> Verify callback
		async (accessToken, refreshToken, profile, done) => {
			//console.log(profile);
			const s64 = Buffer.from(
				`${process.env.TWITTER_CLIENT_ID}:${process.env.TWITTER_CLIENT_SECRET}`
			).toString('base64');
			options.customHeaders = {
				Authorization: ['Basic', s64].join(' '),
			};
			try {
				const { id, _json } = profile;
				const name = _json.name;
				const screen_name = _json.screen_name;
				const followers_count = _json.followers_count;
				const findUser = await TwitterUser.findOne({ twitterId: id });

				if (findUser) {
					console.log('access token', accessToken);
					console.log('tokenSecret', refreshToken);
					findUser.accessToken = jwt.sign(
						{ accessToken },
						process.env.JWT_TWITTER_CLIENT_TOKEN
					);
					findUser.refreshToken = jwt.sign(
						{ refreshToken },
						process.env.JWT_TWITTER_CLIENT_TOKEN_SECRET
					);

					await findUser.save();

					return done(null, findUser);
				} else {
					console.log('access token', accessToken);
					console.log('tokenSecret', refreshToken);
					//console.log('pofileTest',id,name, screen_name,followers_count)
					const newUser = await TwitterUser.create({
						twitterId: id,
						userName: name,
						screenName: screen_name,
						followersCount: followers_count,
						accessToken: jwt.sign(
							{ accessToken },
							process.env.JWT_TWITTER_CLIENT_TOKEN
						),
						refreshToken: jwt.sign(
							{ refreshToken },
							process.env.JWT_TWITTER_CLIENT_TOKEN_SECRET
						),
					});
					return done(null, newUser);
				}
			} catch (error) {
				console.error(error);
				return done(error, null);
			}
		}
	)
);
```

we need to add this in it

```
const s64 = Buffer.from(
				`${process.env.TWITTER_CLIENT_ID}:${process.env.TWITTER_CLIENT_SECRET}`
			).toString('base64');
			options.customHeaders = {
				Authorization: ['Basic', s64].join(' '),
			};
```

thanks a lot mr @janhalama i wish you a good day

**Comment by cSarcasme** [comment]
So i have try many things and if i put in the developer portal on native app public client it work(but i am not sure it is good to do that for security)

I have look inside the module and normally if it is in clientType: 'confidential' the module take the clientID and clientSecret and create himself the header i don t understand why it not work.

I have try myself to add the headers like that too and always the same message


```
passport.use(
	// <2> Strategy initialization
	new Strategy(
		{
			clientID: process.env.TWITTER_CLIENT_ID,
			clientSecret: process.env.TWITTER_CLIENT_ID_SECRET,
			clientType: 'confidential',
			callbackURL: process.env.CALLBACK_TWITTER,
			customHeaders: {
				Authorization:
					'Basic ' +
					Buffer.from(
						`${process.env.TWITTER_CLIENT_ID}:${process.env.TWITTER_CLIENT_ID_SECRET}`
					).toString('base64'),
			},
		},
		// <3> Verify callback
		async (accessToken, refreshToken, profile, done) => {
			console.log('AccessToken:', accessToken);
			console.log('RefreshToken:', refreshToken);
			//console.log('profile', profile);
			try {
				const { id, _json } = profile;
				const name = _json.name;
				const userName = _json.username;

				const findUser = await TwitterUser.findOne({ twitterId: id });

				if (findUser) {
					console.log('access token', accessToken);
					console.log('tokenSecret', refreshToken);
					findUser.accessToken = jwt.sign(
						{ accessToken },
						process.env.JWT_TWITTER_CLIENT_TOKEN
					);
					findUser.refreshToken = jwt.sign(
						{ refreshToken },
						process.env.JWT_TWITTER_CLIENT_TOKEN_SECRET
					);

					await findUser.save();

					return done(null, findUser);
				} else {
					console.log('access token', accessToken);
					console.log('tokenSecret', refreshToken);
					//console.log('pofileTest',id,name, screen_name,followers_count)
					const newUser = await TwitterUser.create({
						twitterId: id,
						name: name,
						username: userName,
						accesstoken: jwt.sign(
							{ accessToken },
							process.env.JWT_TWITTER_CLIENT_TOKEN
						),
						refreshtoken: jwt.sign(
							{ refreshToken },
							process.env.JWT_TWITTER_CLIENT_TOKEN_SECRET
						),
					});
					return done(null, newUser);
				}
			} catch (error) {
				console.error(error);
				return done(error, null);
			}
		}
	)
);
```

I have try to change customHeaders to headers and same issue.

I need to advance on my project (i have the automation quest to do link to twitter) so i will put on public in wait to find a solution but i really need to find it for the security before go to live.

if you see something i have no see tell me ty for your help

**Comment by jfrader** [comment]
I had this issue and the problem was actually my Nginx proxy not forwarding the protocol and I needed to add 

`proxy_set_header X-Forwarded-Proto $scheme; `

to my Nginx configuration


Another possibility is that your cookie is not being set correctly probably becuase of domain or some other settings.

Also if you are behind a proxy you need to trust proxy in express.

**Comment by janhalama** [comment]
@Olliebrown I have not found any problems with the code you provided.

I can simulate the same error response by configuring the X application as confidential, and then setting the `public' client type option in my test client code. This is expected, because in the case of the public client type, the `Authorization' header is not sent.

It is the response on the[ token endpoint](https://datatracker.ietf.org/doc/html/rfc6749#section-3.2) that returns the error. The initial code exchange at the authorization endpoint succeeds.

[RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) defines two different methods of client authentication, the first is the authorization header using the basic auth scheme and the second using body params. The [node-oauth](https://github.com/ciaranj/node-oauth/blob/0749d671f04b684ca255d6ff5340ae3efe711d9a/lib/oauth2.js#L182) lib (used under the hood) implements just body params auth and Twitter accepts just auth header. Google and Facebook OAuth 2.0 implementations accept the body params auth, so you have no problems with them.

Our [sample app](https://github.com/superfaceai/passport-twitter-oauth2/tree/main/examples/basic-usage) works fine for me, have you tried running it on your dev box?

**Comment by Olliebrown** [comment]
@janhalama Thank you for taking the time to look through the code!  I appreciate it.

I have not tried the simple app so I will give that a go.  It is perhaps an issue with my specific box or network environment.  I appreciate the lead to follow.  I'll report back if I find anything to explain what is happening for me.
