### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by kkkkh** [superfaceai/passport-twitter-oauth2#45]
InternalOAuthError: Failed to obtain access token
    at OAuth2Strategy._createOAuthError (/Users/zht/Desktop/TON/t404/server/node_modules/.pnpm/passport-oauth2@1.8.0/node_modules/passport-oauth2/lib/strategy.js:423:17)
    at /Users/zht/Desktop/TON/t404/server/node_modules/.pnpm/passport-oauth2@1.8.0/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /Users/zht/Desktop/TON/t404/server/node_modules/.pnpm/oauth@0.10.0/node_modules/oauth/lib/oauth2.js:196:18
    at ClientRequest.<anonymous> (/Users/zht/Desktop/TON/t404/server/node_modules/.pnpm/oauth@0.10.0/node_modules/oauth/lib/oauth2.js:166:7)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:500:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by janhalama** [comment]
Sorry can not help you here. If you what support please open new issue with better description and minimal reproducible example.
